### ISSUE TITLE
성능테스트 버그

### ISSUE THREAD

**Issue by tmdrl5779** [tmdrl5779/ApiTestProject#5]
1. 처음에 user 100, loop 10을 호출함 > 결과 그래프 및 퍼센트가 90%에서 멈춤 (응답은 다 온걸로 확인됨)
2. 뒤로가기 눌렀다가 다시 호출했을때 아래와 같은 현상 발생

![image](https://github.com/tmdrl5779/ApiTestProject/assets/45285712/983501b6-8189-448a-8379-aff124159911)

![image](https://github.com/tmdrl5779/ApiTestProject/assets/45285712/45e7236a-4689-4c9a-9b22-97e601efb03b)

**Comment by fe-jhw** [comment]
useQueueing 클린업 안하는 버그 수정하여 해결
