### ISSUE TITLE
성능테스트: response 1개일 때 response 별 응답과 repsonse 묶음 응답시간이 다름

### ISSUE THREAD

**Issue by fe-jhw** [tmdrl5779/ApiTestProject#7]
response 1개일 때 response 별 응답과 repsonse 묶음 응답시간이 다름

**Comment by fe-jhw** [comment]
![image](https://github.com/tmdrl5779/ApiTestProject/assets/119602237/14eb0f75-f538-410e-aa0c-b03fa965b8f8)

**Comment by tmdrl5779** [comment]
해결
total Time 계산 로직 변경
